name: CD pipeline with Spring boot

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH 로 EC2 접속하기
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script_stop: true
                  script: |
                      sudo su
                      cd  /home/ubuntu
                      sudo chown -R $USER:$USER /home/ubuntu
                      git config --global --add safe.directory /home/ubuntu
                      git clone https://github.com/CODE-ALPHA-project/be
                  script: |
                      sudo chown -R $USER:$USER /home/***/be
                      git config --global --add safe.directory /home/***/be/spring/be
                      cd /home/***/be
                      git pull origin main
                      ./gradlew clean build
                      cd ..
                      sudo docker-compose up --build -d